#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/NetworkMonitorLLM
dotnet publish  NetworkMonitorLLM.csproj  --os linux --arch x64 /t:PublishContainer -c Release  --self-contained


